### ISSUE TITLE
Default Select Trigger initially does not update when form-control input changes

### ISSUE THREAD

**Issue by JKupski** [Vizer/ngx-virtual-select-field#10]
When setting a value on the select with a timeout, the trigger text in the select does not update, when not opened before.

Test on: https://stackblitz.com/edit/demo-ngx-virtual-select-field-ucxg9a?file=src%2Fdemo-virtual-select-field%2Fdemo-virtual-select-field.component.html 
Example 5 with the ngx-component and example 8 with the native select. Currently trying to figure out the problem

**Comment by JKupski** [comment]
@Vizer if you have any idea where this problem arises I'd appreciate :)

**Comment by Vizer** [comment]
@JKupski, thank you for posting an issue, I will check  it out later this week. Will try to fix it
