### ISSUE TITLE
Value changes not synced to the panel while it's open

### ISSUE THREAD

**Issue by Klaster1** [Vizer/ngx-virtual-select-field#2]
How to reproduce:
1. Bind the select value to a form control.
2. Modify the form control value on value change.
3. Select a value.

What happens:
Trigger value shows the new value. Panel shows the old value.

Expected:
Both trigger and panel show the same new value. Regular `mat-select` works this way too.

[Blitz](https://stackblitz.com/edit/demo-ngx-virtual-select-field-hahup6?file=src%2Fdemo-virtual-select-field%2Fdemo-virtual-select-field.component.ts).

**Comment by Vizer** [comment]
Not sure I have got you right but in a demo you have provided component binds to `control` but hint renders `customOptionHeightValue`

Demo:
```html
<mat-hint>Value: {{ customOptionHeightValue }}</mat-hint>
```
Should be 
```html
<mat-hint>Value: {{ control.value }}</mat-hint>
```

Also in multiselect mode control value should be an array
```typescript
control = new FormControl<number[]>([0]);
```

**Comment by Klaster1** [comment]
My bad, I messed up the Blitz with all those issues. Here's an [updated one](https://stackblitz.com/edit/demo-ngx-virtual-select-field-mf5glr?file=src%2Fdemo-virtual-select-field%2Fdemo-virtual-select-field.component.html,src%2Fdemo-virtual-select-field%2Fdemo-virtual-select-field.component.ts,src%2Fdemo-virtual-select-field%2Fdemo-virtual-select-field.component.css) and a video. I expected `ngx-virtual-select-field` (left) to behave in the same manner as `mat-select` (right).

https://github.com/Vizer/ngx-virtual-select-field/assets/2667662/a77ed8bb-ff18-42d9-a376-049dce390dec
