### ISSUE TITLE
Styles broken with Angular 17

### ISSUE THREAD

**Issue by Klaster1** [Vizer/ngx-virtual-select-field#3]
How to reproduce:
1. Use the library in an Angular 17 with a Material 2 theme.
2. Open the select.

What happens:
Most of the colors are missing because stylesheets use unavailable CSS variables. I had to re-assign variables to closest matching ones.

Expected:
The component is fully styles in Angular 17 Material 2 apps.

Notes:
How about introducing a theme mixing specifically for this use case?

Feel free to disregard the issue if you believe the library doesn't need to support Angular 17.

**Comment by Vizer** [comment]
It should work with angular 17, which exactly angular and material version did you try?

**Comment by Klaster1** [comment]
I'll try to prepare a repro in a couple of days, no problem. Maybe the mistake was on my part 😅

**Comment by Klaster1** [comment]
False alarm, it was me: the app had themes applied to `body` instead of `:root`, so nothing worked.
