### ISSUE TITLE
Panel lacks start and end paddings as seen in mat-select

### ISSUE THREAD

**Issue by Klaster1** [Vizer/ngx-virtual-select-field#4]
How to reproduce:
Open the select panel.

Expected:
The panel has same paddings as `mat-select`:
![image](https://github.com/Vizer/ngx-virtual-select-field/assets/2667662/000b6293-42da-4e86-a3ac-43d7692e36ab)

Observed:
No paddings;
![image](https://github.com/Vizer/ngx-virtual-select-field/assets/2667662/8bb9937e-9a37-43be-bbdf-5f6315e84bd9)

**Comment by Klaster1** [comment]
The panel height calculation does not take padding into account, here's a workaround:
```
height: calc(var(--ngx-virtual-select-field-panel-option-height)* var(--ngx-virtual-select-field-panel-viewport-page-size) + 16px);
```

**Comment by Vizer** [comment]
thanks, I have encountered on this too
